window.esdocSearchIndex = [
  [
    "@functional-abstraction/type/src/isarray.js~isarray",
    "function/index.html#static-function-isArray",
    "<span>isArray</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isArray.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isboolean.js~isboolean",
    "function/index.html#static-function-isBoolean",
    "<span>isBoolean</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isBoolean.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isdate.js~isdate",
    "function/index.html#static-function-isDate",
    "<span>isDate</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isDate.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isfinite.js~isfinite",
    "function/index.html#static-function-isFinite",
    "<span>isFinite</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isFinite.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isfunction.js~isfunction",
    "function/index.html#static-function-isFunction",
    "<span>isFunction</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isFunction.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isinstance.js~isinstance",
    "function/index.html#static-function-isInstance",
    "<span>isInstance</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isInstance.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isint32.js~isint32",
    "function/index.html#static-function-isInt32",
    "<span>isInt32</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isInt32.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isint.js~isint",
    "function/index.html#static-function-isInt",
    "<span>isInt</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isInt.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isnan.js~isnan",
    "function/index.html#static-function-isNaN",
    "<span>isNaN</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isNaN.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isnegativeinfinity.js~isnegativeinfinity",
    "function/index.html#static-function-isNegativeInfinity",
    "<span>isNegativeInfinity</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isNegativeInfinity.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isnull.js~isnull",
    "function/index.html#static-function-isNull",
    "<span>isNull</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isNull.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isnumber.js~isnumber",
    "function/index.html#static-function-isNumber",
    "<span>isNumber</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isNumber.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isobject.js~isobject",
    "function/index.html#static-function-isObject",
    "<span>isObject</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isObject.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/ispositiveinfinity.js~ispositiveinfinity",
    "function/index.html#static-function-isPositiveInfinity",
    "<span>isPositiveInfinity</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isPositiveInfinity.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isregexp.js~isregexp",
    "function/index.html#static-function-isRegExp",
    "<span>isRegExp</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isRegExp.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isstring.js~isstring",
    "function/index.html#static-function-isString",
    "<span>isString</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isString.js</span>",
    "function"
  ],
  [
    "@functional-abstraction/type/src/isundefined.js~isundefined",
    "function/index.html#static-function-isUndefined",
    "<span>isUndefined</span> <span class=\"search-result-import-path\">@functional-abstraction/type/src/isUndefined.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/isarray.js",
    "file/src/isArray.js.html",
    "src/isArray.js",
    "file"
  ],
  [
    "src/isboolean.js",
    "file/src/isBoolean.js.html",
    "src/isBoolean.js",
    "file"
  ],
  [
    "src/isdate.js",
    "file/src/isDate.js.html",
    "src/isDate.js",
    "file"
  ],
  [
    "src/isfinite.js",
    "file/src/isFinite.js.html",
    "src/isFinite.js",
    "file"
  ],
  [
    "src/isfunction.js",
    "file/src/isFunction.js.html",
    "src/isFunction.js",
    "file"
  ],
  [
    "src/isinstance.js",
    "file/src/isInstance.js.html",
    "src/isInstance.js",
    "file"
  ],
  [
    "src/isint.js",
    "file/src/isInt.js.html",
    "src/isInt.js",
    "file"
  ],
  [
    "src/isint32.js",
    "file/src/isInt32.js.html",
    "src/isInt32.js",
    "file"
  ],
  [
    "src/isnan.js",
    "file/src/isNaN.js.html",
    "src/isNaN.js",
    "file"
  ],
  [
    "src/isnegativeinfinity.js",
    "file/src/isNegativeInfinity.js.html",
    "src/isNegativeInfinity.js",
    "file"
  ],
  [
    "src/isnull.js",
    "file/src/isNull.js.html",
    "src/isNull.js",
    "file"
  ],
  [
    "src/isnumber.js",
    "file/src/isNumber.js.html",
    "src/isNumber.js",
    "file"
  ],
  [
    "src/isobject.js",
    "file/src/isObject.js.html",
    "src/isObject.js",
    "file"
  ],
  [
    "src/ispositiveinfinity.js",
    "file/src/isPositiveInfinity.js.html",
    "src/isPositiveInfinity.js",
    "file"
  ],
  [
    "src/isregexp.js",
    "file/src/isRegExp.js.html",
    "src/isRegExp.js",
    "file"
  ],
  [
    "src/isstring.js",
    "file/src/isString.js.html",
    "src/isString.js",
    "file"
  ],
  [
    "src/isundefined.js",
    "file/src/isUndefined.js.html",
    "src/isUndefined.js",
    "file"
  ]
]